#pragma once

#include "CalamityAffixes/LootRollSelection.h"
#include "CalamityAffixes/LootCurrencyLedger.h"
#include "CalamityAffixes/LootSlotSanitizer.h"
#include "CalamityAffixes/LootUiGuards.h"
#include "CalamityAffixes/LootRerollGuard.h"
#include "CalamityAffixes/NonHostileFirstHitGate.h"
#include "CalamityAffixes/LowHealthTriggerSnapshot.h"
#include "CalamityAffixes/PerTargetCooldownStore.h"
#include "CalamityAffixes/RuntimeUserSettingsDebounce.h"
#include "CalamityAffixes/Hooks.h"
#include "CalamityAffixes/RuntimePolicy.h"
#include "CalamityAffixes/RunewordUiPolicy.h"
#include "CalamityAffixes/TriggerGuards.h"

#include <algorithm>
#include <array>
#include <chrono>
#include <cmath>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <optional>
#include <random>
#include <string>
#include <vector>

namespace RuntimeGateStoreChecks
{
	bool CheckNonHostileFirstHitGate();
	bool CheckPerTargetCooldownStore();
	bool CheckHandleHealthDamageVfuncIndexPolicy();
	bool CheckHooksDispatchExtractionPolicy();
	bool CheckPluginLoggingExceptionSafetyPolicy();
	bool CheckRebuildActiveCountsLoggingPolicy();
	bool CheckRebuildActiveCountsExtractionPolicy();
	bool CheckHealthDamageSignatureWindowPolicy();
	bool CheckHealthDamageGuardHelperFlow();
	bool CheckTesHitFallbackSourceValidationPolicy();
	bool CheckBloomTrapProcFeedbackPolicy();
	bool CheckConfigLoadPipelineExtractionPolicy();
	bool CheckHybridCurrencyDropPolicy();
	bool CheckAffixSpecialActionStateExtractionPolicy();
	bool CheckTriggerProcPolicyExtraction();
	bool CheckProcessTriggerExtractionPolicy();
	bool CheckUniformLootRollSelection();
	bool CheckShuffleBagLootRollSelection();
	bool CheckWeightedShuffleBagLootRollSelection();
	bool CheckFixedWindowBudget();
	bool CheckRecentlyAndLuckyHitGuards();
	bool CheckShuffleBagSanitizeAndRollConstraints();
	bool CheckLootSlotSanitizer();

	bool CheckRunewordTooltipOverlayPolicy();
	bool CheckLootPreviewRuntimePolicy();
	bool CheckLootServiceExtractionPolicy();
	bool CheckLootDisplayNameExtractionPolicy();
	bool CheckLootTrackedSanitizeExtractionPolicy();
	bool CheckLootSlotSanitizeHelperExtractionPolicy();
	bool CheckLootRerollExploitGuardPolicy();
	bool CheckLootCurrencyLedgerSerializationPolicy();
	bool CheckLootEligibilityCleanupSafetyPolicy();
	bool CheckSuffixProcChanceParsingPolicy();
	bool CheckSerializationDrainSafetyPolicy();
	bool CheckSpecialActionProcSafetyPolicy();
	bool CheckCorpseExplosionBudgetSafetyPolicy();
	bool CheckSerializationTransientRuntimeResetPolicy();
	bool CheckLootChanceMcmCleanupPolicy();
	bool CheckMcmDropChanceRuntimeBridgePolicy();

	bool CheckRunewordCompletedSelectionPolicy();
	bool CheckRunewordRecipeEntriesMappingPolicy();
	bool CheckRunewordRecipeTooltipTextPolicy();
	bool CheckRunewordUiContractExtractionPolicy();
	bool CheckRunewordRuntimeStateExtractionPolicy();
	bool CheckRunewordCoverageConsistencyPolicy();
	bool CheckAffixRegistryStateExtractionPolicy();
	bool CheckLowHealthTriggerSnapshotPolicy();
	bool CheckRunewordRecipeRuntimeEligibilityPolicy();
	bool CheckRunewordContractSnapshotPolicy();
	bool CheckSynthesizedAffixDisplayNameFallbackPolicy();
	bool CheckSynthesizedRunewordTooltipSummaryPolicy();
	bool CheckRunewordTransmuteSafetyPolicy();
	bool CheckRunewordUiPolicyHelpers();
	bool CheckRunewordReforgeSafetyPolicy();
	bool CheckPrismaTooltipImmediateRefreshPolicy();
	bool CheckPrismaPanelUiBootstrapExtractionPolicy();
	bool CheckPrismaPanelRenderViewModelExtractionPolicy();
	bool CheckPrismaPanelUxFlowPolicy();
	bool CheckPrismaPanelDataExtractionPolicy();
	bool CheckPrismaPanelCommandRoutingExtractionPolicy();
	bool CheckPrismaTooltipLifecycleExtractionPolicy();
	bool CheckPrismaSettingsLayoutExtractionPolicy();
	bool CheckPrismaTooltipWorkerSchedulingPolicy();
	bool CheckPrismaTooltipTelemetryPolicy();

	bool CheckRuntimeUserSettingsDebounceBehavior();
	bool CheckExternalUserSettingsPersistencePolicy();
	bool CheckRuntimeUserSettingsRoundTripFieldPolicy();
	bool CheckPlayerHealthDamageHookDefaultPolicy();
	bool CheckEventBridgeStateMutexReentrancyPolicy();
	bool CheckCombatRuntimeStateResetBehavior();
	bool CheckCombatRuntimeStateExtractionPolicy();
	bool CheckLootRuntimeStateResetBehavior();
	bool CheckLootRuntimeStateExtractionPolicy();
	bool CheckConfigReloadTransientRuntimeResetPolicy();
	bool CheckRunewordUiContractDefaults();

	bool CheckPerTargetCooldownStorePruning();
	bool CheckPerTargetCooldownStoreIndependence();
	bool CheckNonHostileFirstHitGateTtlExpiry();
	bool CheckNonHostileFirstHitGateCapacityEviction();
	bool CheckLootRerollGuardLifecycle();
	bool CheckLootRerollGuardCircularOverflow();
	bool CheckLootRerollGuardEdgeCases();
	bool CheckSerializationLoadStateHelpers();
	bool CheckLowHealthTriggerSnapshotHelpers();
}
