using System.Text;
using CalamityAffixes.Generator.Spec;

namespace CalamityAffixes.Generator.Writers;

public static class SpidIniWriter
{
    public static string Render(AffixSpec spec)
    {
        var sb = new StringBuilder();
        sb.AppendLine("; CalamityAffixes_DISTR.ini (AUTOGENERATED)");
        sb.AppendLine($"; Generated: {DateTimeOffset.UtcNow:O}");
        sb.AppendLine("; NOTE: filename must end with \"_DISTR.ini\" and live in Skyrim's Data folder.");
        sb.AppendLine("; DO NOT EDIT BY HAND. Edit affixes/affixes.json and re-run generator.");
        sb.AppendLine();

        foreach (var rule in spec.Keywords.SpidRules)
        {
            if (rule.TryGetValue("comment", out var commentObj) &&
                commentObj is string comment &&
                !string.IsNullOrWhiteSpace(comment))
            {
                sb.AppendLine($"; {comment}");
            }

            if (rule.TryGetValue("line", out var lineObj) &&
                lineObj is string line &&
                !string.IsNullOrWhiteSpace(line))
            {
                sb.AppendLine(line);
            }
        }

        if (spec.Keywords.SpidRules.Count > 0)
        {
            sb.AppendLine();
        }

        return sb.ToString();
    }
}
