using System.Text;
using System.Text.Json;
using CalamityAffixes.Generator.Spec;

namespace CalamityAffixes.Generator.Writers;

public static class SpidIniWriter
{
    public static string Render(AffixSpec spec)
    {
        var sb = new StringBuilder();
        sb.AppendLine("; CalamityAffixes_DISTR.ini (AUTOGENERATED)");
        sb.AppendLine($"; Generated: {DateTimeOffset.UtcNow:O}");
        sb.AppendLine("; NOTE: filename must end with \"_DISTR.ini\" and live in Skyrim's Data folder.");
        sb.AppendLine("; DO NOT EDIT BY HAND. Edit affixes/modules/*.json (or affixes/affixes.json) and re-run generator.");
        sb.AppendLine();

        foreach (var rule in spec.Keywords.SpidRules)
        {
            if (TryReadRuleString(rule, "comment", out var comment))
            {
                sb.AppendLine($"; {comment}");
            }

            if (TryReadRuleString(rule, "line", out var line))
            {
                sb.AppendLine(line);
            }
        }

        if (spec.Keywords.SpidRules.Count > 0)
        {
            sb.AppendLine();
        }

        return sb.ToString();
    }

    private static bool TryReadRuleString(
        IReadOnlyDictionary<string, object?> rule,
        string key,
        out string value)
    {
        value = string.Empty;
        if (!rule.TryGetValue(key, out var raw) || raw is null)
        {
            return false;
        }

        switch (raw)
        {
            case string s when !string.IsNullOrWhiteSpace(s):
                value = s;
                return true;
            case JsonElement element when element.ValueKind == JsonValueKind.String:
                var jsonText = element.GetString();
                if (!string.IsNullOrWhiteSpace(jsonText))
                {
                    value = jsonText;
                    return true;
                }
                return false;
            default:
                return false;
        }
    }
}
